services:
  db:
    image: postgres:14
    container_name: sue-shop-db
    restart: always
    environment:
      POSTGRES_USER: susan
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: susan
    volumes:
      - sue-shop_pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    image: iyewumi89/sue-shop-backend:latest
    container_name: sue-shop-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    image: iyewumi89/sue-shop-frontend:latest
    container_name: sue-shop-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  sue-shop_pgdata:

networks:
  app-network:
    driver: bridge