services:
  db:
    image: postgres:14
    container_name: sue-shop-db
    restart: always
    environment:
      POSTGRES_USER: susan
      POSTGRES_PASSWORD: sall_suz@57
      POSTGRES_DB: susan
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U susan"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - sue-shop_pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: sue-shop-backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile
    container_name: sue-shop-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/my-app:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  sue-shop_pgdata:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge